version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.12
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: on-failure
    command: 
      [
        "--log-level=error"
      ]
    depends_on:
        - elasticsearch

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.12
    command: 
      [
          "--reporter.grpc.host-port=jaeger-collector:14250"
      ]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.12
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    command: 
      [
          "--es.server-urls=http://elasticsearch:9200", 
          "--span-storage.type=elasticsearch", 
          "--log-level=debug",
          "--es.sniffer=false",
      ]
    depends_on:
      - elasticsearch
      - jaeger-agent
